import React from 'react';

import Header from '../../layout/Header';
import Curriculum from '../../layout/dropdown/Curriculum';

import Table from 'react-bootstrap/Table';

const CurriculumMenu = () => {
  return (
    <div>
      <Header text={'영어캠프'} sub={'식단표'} />

      <div className='container'>
        <div className='pageGrid'>
          <div className='page-g1'>
            <div className='sideTitle'>영어캠프</div>
            <Curriculum current={'menu'} />
          </div>
          <div className='page-g2'>
            <div className='pageTitle'>
              <span className='subTitleNav'>식단표</span>
            </div>
            <div className='currMenu'>
              <div className='currMenuPanel'>
                <div className='weekTitle'>4주</div>
                <div className='weekTitle'>6주</div>
                <div className='weekTitle'>8주</div>
              </div>
              <div className='currMenuTable'>
                <div className='currMenuWeek text-center'>
                  <Table striped bordered>
                    <thead>
                      <tr>
                        <th>1주</th>
                        <th>1/1 (일)</th>
                        <th>1/2 (월)</th>
                        <th>1/3 (화)</th>
                        <th>1/4 (수)</th>
                        <th>1/5 (목)</th>
                        <th>1/6 (금)</th>
                        <th>1/7 (토)</th>
                      </tr>
                    </thead>
                    <tbody>
                      <tr>
                        <td>아침</td>
                        <td>
                          <ul>
                            <li>쌀밥</li>
                            <li>소고기무국</li>
                            <li>야채계란찜</li>
                            <li>열무순나물</li>
                            <li>김치/요구르트</li>
                            <li>미역국</li>
                          </ul>
                        </td>
                        <td>
                          <ul>
                            <li>쌀밥</li>
                            <li>소고기무국</li>
                            <li>야채계란찜</li>
                            <li>열무순나물</li>
                            <li>김치/요구르트</li>
                            <li>미역국</li>
                          </ul>
                        </td>
                        <td>
                          <ul>
                            <li>쌀밥</li>
                            <li>소고기무국</li>
                            <li>야채계란찜</li>
                            <li>열무순나물</li>
                            <li>김치/요구르트</li>
                            <li>미역국</li>
                          </ul>
                        </td>
                        <td>
                          <ul>
                            <li>쌀밥</li>
                            <li>소고기무국</li>
                            <li>야채계란찜</li>
                            <li>열무순나물</li>
                            <li>김치/요구르트</li>
                            <li>미역국</li>
                          </ul>
                        </td>
                        <td>
                          <ul>
                            <li>쌀밥</li>
                            <li>소고기무국</li>
                            <li>야채계란찜</li>
                            <li>열무순나물</li>
                            <li>김치/요구르트</li>
                            <li>미역국</li>
                          </ul>
                        </td>
                        <td>
                          <ul>
                            <li>쌀밥</li>
                            <li>소고기무국</li>
                            <li>야채계란찜</li>
                            <li>열무순나물</li>
                            <li>김치/요구르트</li>
                            <li>미역국</li>
                          </ul>
                        </td>
                        <td>
                          <ul>
                            <li>쌀밥</li>
                            <li>소고기무국</li>
                            <li>야채계란찜</li>
                            <li>열무순나물</li>
                            <li>김치/요구르트</li>
                            <li>미역국</li>
                          </ul>
                        </td>
                      </tr>
                      <tr>
                        <td>점심</td>
                        <td>
                          <ul>
                            <li>쌀밥</li>
                            <li>소고기무국</li>
                            <li>야채계란찜</li>
                            <li>열무순나물</li>
                            <li>김치/요구르트</li>
                            <li>미역국</li>
                          </ul>
                        </td>
                        <td>
                          <ul>
                            <li>쌀밥</li>
                            <li>소고기무국</li>
                            <li>야채계란찜</li>
                            <li>열무순나물</li>
                            <li>김치/요구르트</li>
                            <li>미역국</li>
                          </ul>
                        </td>
                        <td>
                          <ul>
                            <li>쌀밥</li>
                            <li>소고기무국</li>
                            <li>야채계란찜</li>
                            <li>열무순나물</li>
                            <li>김치/요구르트</li>
                            <li>미역국</li>
                          </ul>
                        </td>
                        <td>
                          <ul>
                            <li>쌀밥</li>
                            <li>소고기무국</li>
                            <li>야채계란찜</li>
                            <li>열무순나물</li>
                            <li>김치/요구르트</li>
                            <li>미역국</li>
                          </ul>
                        </td>
                        <td>
                          <ul>
                            <li>쌀밥</li>
                            <li>소고기무국</li>
                            <li>야채계란찜</li>
                            <li>열무순나물</li>
                            <li>김치/요구르트</li>
                            <li>미역국</li>
                          </ul>
                        </td>
                        <td>
                          <ul>
                            <li>쌀밥</li>
                            <li>소고기무국</li>
                            <li>야채계란찜</li>
                            <li>열무순나물</li>
                            <li>김치/요구르트</li>
                            <li>미역국</li>
                          </ul>
                        </td>
                        <td>
                          <ul>
                            <li>쌀밥</li>
                            <li>소고기무국</li>
                            <li>야채계란찜</li>
                            <li>열무순나물</li>
                            <li>김치/요구르트</li>
                            <li>미역국</li>
                          </ul>
                        </td>
                      </tr>
                      <tr>
                        <td>저녁</td>
                        <td>
                          <ul>
                            <li>쌀밥</li>
                            <li>소고기무국</li>
                            <li>야채계란찜</li>
                            <li>열무순나물</li>
                            <li>김치/요구르트</li>
                            <li>미역국</li>
                          </ul>
                        </td>
                        <td>
                          <ul>
                            <li>쌀밥</li>
                            <li>소고기무국</li>
                            <li>야채계란찜</li>
                            <li>열무순나물</li>
                            <li>김치/요구르트</li>
                            <li>미역국</li>
                          </ul>
                        </td>
                        <td>
                          <ul>
                            <li>쌀밥</li>
                            <li>소고기무국</li>
                            <li>야채계란찜</li>
                            <li>열무순나물</li>
                            <li>김치/요구르트</li>
                            <li>미역국</li>
                          </ul>
                        </td>
                        <td>
                          <ul>
                            <li>쌀밥</li>
                            <li>소고기무국</li>
                            <li>야채계란찜</li>
                            <li>열무순나물</li>
                            <li>김치/요구르트</li>
                            <li>미역국</li>
                          </ul>
                        </td>
                        <td>
                          <ul>
                            <li>쌀밥</li>
                            <li>소고기무국</li>
                            <li>야채계란찜</li>
                            <li>열무순나물</li>
                            <li>김치/요구르트</li>
                            <li>미역국</li>
                          </ul>
                        </td>
                        <td>
                          <ul>
                            <li>쌀밥</li>
                            <li>소고기무국</li>
                            <li>야채계란찜</li>
                            <li>열무순나물</li>
                            <li>김치/요구르트</li>
                            <li>미역국</li>
                          </ul>
                        </td>
                        <td>
                          <ul>
                            <li>쌀밥</li>
                            <li>소고기무국</li>
                            <li>야채계란찜</li>
                            <li>열무순나물</li>
                            <li>김치/요구르트</li>
                            <li>미역국</li>
                          </ul>
                        </td>
                      </tr>
                    </tbody>
                  </Table>

                  <Table striped bordered>
                    <thead>
                      <tr>
                        <th>2주</th>
                        <th>1/8 (일)</th>
                        <th>1/9 (월)</th>
                        <th>1/10 (화)</th>
                        <th>1/11 (수)</th>
                        <th>1/12 (목)</th>
                        <th>1/13 (금)</th>
                        <th>1/14 (토)</th>
                      </tr>
                    </thead>
                    <tbody>
                      <tr>
                        <td>아침</td>
                        <td>
                          <ul>
                            <li>쌀밥</li>
                            <li>소고기무국</li>
                            <li>야채계란찜</li>
                            <li>열무순나물</li>
                            <li>김치/요구르트</li>
                            <li>미역국</li>
                          </ul>
                        </td>
                        <td>
                          <ul>
                            <li>쌀밥</li>
                            <li>소고기무국</li>
                            <li>야채계란찜</li>
                            <li>열무순나물</li>
                            <li>김치/요구르트</li>
                            <li>미역국</li>
                          </ul>
                        </td>
                        <td>
                          <ul>
                            <li>쌀밥</li>
                            <li>소고기무국</li>
                            <li>야채계란찜</li>
                            <li>열무순나물</li>
                            <li>김치/요구르트</li>
                            <li>미역국</li>
                          </ul>
                        </td>
                        <td>
                          <ul>
                            <li>쌀밥</li>
                            <li>소고기무국</li>
                            <li>야채계란찜</li>
                            <li>열무순나물</li>
                            <li>김치/요구르트</li>
                            <li>미역국</li>
                          </ul>
                        </td>
                        <td>
                          <ul>
                            <li>쌀밥</li>
                            <li>소고기무국</li>
                            <li>야채계란찜</li>
                            <li>열무순나물</li>
                            <li>김치/요구르트</li>
                            <li>미역국</li>
                          </ul>
                        </td>
                        <td>
                          <ul>
                            <li>쌀밥</li>
                            <li>소고기무국</li>
                            <li>야채계란찜</li>
                            <li>열무순나물</li>
                            <li>김치/요구르트</li>
                            <li>미역국</li>
                          </ul>
                        </td>
                        <td>
                          <ul>
                            <li>쌀밥</li>
                            <li>소고기무국</li>
                            <li>야채계란찜</li>
                            <li>열무순나물</li>
                            <li>김치/요구르트</li>
                            <li>미역국</li>
                          </ul>
                        </td>
                      </tr>
                      <tr>
                        <td>점심</td>
                        <td>
                          <ul>
                            <li>쌀밥</li>
                            <li>소고기무국</li>
                            <li>야채계란찜</li>
                            <li>열무순나물</li>
                            <li>김치/요구르트</li>
                            <li>미역국</li>
                          </ul>
                        </td>
                        <td>
                          <ul>
                            <li>쌀밥</li>
                            <li>소고기무국</li>
                            <li>야채계란찜</li>
                            <li>열무순나물</li>
                            <li>김치/요구르트</li>
                            <li>미역국</li>
                          </ul>
                        </td>
                        <td>
                          <ul>
                            <li>쌀밥</li>
                            <li>소고기무국</li>
                            <li>야채계란찜</li>
                            <li>열무순나물</li>
                            <li>김치/요구르트</li>
                            <li>미역국</li>
                          </ul>
                        </td>
                        <td>
                          <ul>
                            <li>쌀밥</li>
                            <li>소고기무국</li>
                            <li>야채계란찜</li>
                            <li>열무순나물</li>
                            <li>김치/요구르트</li>
                            <li>미역국</li>
                          </ul>
                        </td>
                        <td>
                          <ul>
                            <li>쌀밥</li>
                            <li>소고기무국</li>
                            <li>야채계란찜</li>
                            <li>열무순나물</li>
                            <li>김치/요구르트</li>
                            <li>미역국</li>
                          </ul>
                        </td>
                        <td>
                          <ul>
                            <li>쌀밥</li>
                            <li>소고기무국</li>
                            <li>야채계란찜</li>
                            <li>열무순나물</li>
                            <li>김치/요구르트</li>
                            <li>미역국</li>
                          </ul>
                        </td>
                        <td>
                          <ul>
                            <li>쌀밥</li>
                            <li>소고기무국</li>
                            <li>야채계란찜</li>
                            <li>열무순나물</li>
                            <li>김치/요구르트</li>
                            <li>미역국</li>
                          </ul>
                        </td>
                      </tr>
                      <tr>
                        <td>저녁</td>
                        <td>
                          <ul>
                            <li>쌀밥</li>
                            <li>소고기무국</li>
                            <li>야채계란찜</li>
                            <li>열무순나물</li>
                            <li>김치/요구르트</li>
                            <li>미역국</li>
                          </ul>
                        </td>
                        <td>
                          <ul>
                            <li>쌀밥</li>
                            <li>소고기무국</li>
                            <li>야채계란찜</li>
                            <li>열무순나물</li>
                            <li>김치/요구르트</li>
                            <li>미역국</li>
                          </ul>
                        </td>
                        <td>
                          <ul>
                            <li>쌀밥</li>
                            <li>소고기무국</li>
                            <li>야채계란찜</li>
                            <li>열무순나물</li>
                            <li>김치/요구르트</li>
                            <li>미역국</li>
                          </ul>
                        </td>
                        <td>
                          <ul>
                            <li>쌀밥</li>
                            <li>소고기무국</li>
                            <li>야채계란찜</li>
                            <li>열무순나물</li>
                            <li>김치/요구르트</li>
                            <li>미역국</li>
                          </ul>
                        </td>
                        <td>
                          <ul>
                            <li>쌀밥</li>
                            <li>소고기무국</li>
                            <li>야채계란찜</li>
                            <li>열무순나물</li>
                            <li>김치/요구르트</li>
                            <li>미역국</li>
                          </ul>
                        </td>
                        <td>
                          <ul>
                            <li>쌀밥</li>
                            <li>소고기무국</li>
                            <li>야채계란찜</li>
                            <li>열무순나물</li>
                            <li>김치/요구르트</li>
                            <li>미역국</li>
                          </ul>
                        </td>
                        <td>
                          <ul>
                            <li>쌀밥</li>
                            <li>소고기무국</li>
                            <li>야채계란찜</li>
                            <li>열무순나물</li>
                            <li>김치/요구르트</li>
                            <li>미역국</li>
                          </ul>
                        </td>
                      </tr>
                    </tbody>
                  </Table>

                  <Table striped bordered>
                    <thead>
                      <tr>
                        <th>3주</th>
                        <th>1/15 (일)</th>
                        <th>1/16 (월)</th>
                        <th>1/17 (화)</th>
                        <th>1/18 (수)</th>
                        <th>1/19 (목)</th>
                        <th>1/20 (금)</th>
                        <th>1/21 (토)</th>
                      </tr>
                    </thead>
                    <tbody>
                      <tr>
                        <td>아침</td>
                        <td>
                          <ul>
                            <li>쌀밥</li>
                            <li>소고기무국</li>
                            <li>야채계란찜</li>
                            <li>열무순나물</li>
                            <li>김치/요구르트</li>
                            <li>미역국</li>
                          </ul>
                        </td>
                        <td>
                          <ul>
                            <li>쌀밥</li>
                            <li>소고기무국</li>
                            <li>야채계란찜</li>
                            <li>열무순나물</li>
                            <li>김치/요구르트</li>
                            <li>미역국</li>
                          </ul>
                        </td>
                        <td>
                          <ul>
                            <li>쌀밥</li>
                            <li>소고기무국</li>
                            <li>야채계란찜</li>
                            <li>열무순나물</li>
                            <li>김치/요구르트</li>
                            <li>미역국</li>
                          </ul>
                        </td>
                        <td>
                          <ul>
                            <li>쌀밥</li>
                            <li>소고기무국</li>
                            <li>야채계란찜</li>
                            <li>열무순나물</li>
                            <li>김치/요구르트</li>
                            <li>미역국</li>
                          </ul>
                        </td>
                        <td>
                          <ul>
                            <li>쌀밥</li>
                            <li>소고기무국</li>
                            <li>야채계란찜</li>
                            <li>열무순나물</li>
                            <li>김치/요구르트</li>
                            <li>미역국</li>
                          </ul>
                        </td>
                        <td>
                          <ul>
                            <li>쌀밥</li>
                            <li>소고기무국</li>
                            <li>야채계란찜</li>
                            <li>열무순나물</li>
                            <li>김치/요구르트</li>
                            <li>미역국</li>
                          </ul>
                        </td>
                        <td>
                          <ul>
                            <li>쌀밥</li>
                            <li>소고기무국</li>
                            <li>야채계란찜</li>
                            <li>열무순나물</li>
                            <li>김치/요구르트</li>
                            <li>미역국</li>
                          </ul>
                        </td>
                      </tr>
                      <tr>
                        <td>점심</td>
                        <td>
                          <ul>
                            <li>쌀밥</li>
                            <li>소고기무국</li>
                            <li>야채계란찜</li>
                            <li>열무순나물</li>
                            <li>김치/요구르트</li>
                            <li>미역국</li>
                          </ul>
                        </td>
                        <td>
                          <ul>
                            <li>쌀밥</li>
                            <li>소고기무국</li>
                            <li>야채계란찜</li>
                            <li>열무순나물</li>
                            <li>김치/요구르트</li>
                            <li>미역국</li>
                          </ul>
                        </td>
                        <td>
                          <ul>
                            <li>쌀밥</li>
                            <li>소고기무국</li>
                            <li>야채계란찜</li>
                            <li>열무순나물</li>
                            <li>김치/요구르트</li>
                            <li>미역국</li>
                          </ul>
                        </td>
                        <td>
                          <ul>
                            <li>쌀밥</li>
                            <li>소고기무국</li>
                            <li>야채계란찜</li>
                            <li>열무순나물</li>
                            <li>김치/요구르트</li>
                            <li>미역국</li>
                          </ul>
                        </td>
                        <td>
                          <ul>
                            <li>쌀밥</li>
                            <li>소고기무국</li>
                            <li>야채계란찜</li>
                            <li>열무순나물</li>
                            <li>김치/요구르트</li>
                            <li>미역국</li>
                          </ul>
                        </td>
                        <td>
                          <ul>
                            <li>쌀밥</li>
                            <li>소고기무국</li>
                            <li>야채계란찜</li>
                            <li>열무순나물</li>
                            <li>김치/요구르트</li>
                            <li>미역국</li>
                          </ul>
                        </td>
                        <td>
                          <ul>
                            <li>쌀밥</li>
                            <li>소고기무국</li>
                            <li>야채계란찜</li>
                            <li>열무순나물</li>
                            <li>김치/요구르트</li>
                            <li>미역국</li>
                          </ul>
                        </td>
                      </tr>
                      <tr>
                        <td>저녁</td>
                        <td>
                          <ul>
                            <li>쌀밥</li>
                            <li>소고기무국</li>
                            <li>야채계란찜</li>
                            <li>열무순나물</li>
                            <li>김치/요구르트</li>
                            <li>미역국</li>
                          </ul>
                        </td>
                        <td>
                          <ul>
                            <li>쌀밥</li>
                            <li>소고기무국</li>
                            <li>야채계란찜</li>
                            <li>열무순나물</li>
                            <li>김치/요구르트</li>
                            <li>미역국</li>
                          </ul>
                        </td>
                        <td>
                          <ul>
                            <li>쌀밥</li>
                            <li>소고기무국</li>
                            <li>야채계란찜</li>
                            <li>열무순나물</li>
                            <li>김치/요구르트</li>
                            <li>미역국</li>
                          </ul>
                        </td>
                        <td>
                          <ul>
                            <li>쌀밥</li>
                            <li>소고기무국</li>
                            <li>야채계란찜</li>
                            <li>열무순나물</li>
                            <li>김치/요구르트</li>
                            <li>미역국</li>
                          </ul>
                        </td>
                        <td>
                          <ul>
                            <li>쌀밥</li>
                            <li>소고기무국</li>
                            <li>야채계란찜</li>
                            <li>열무순나물</li>
                            <li>김치/요구르트</li>
                            <li>미역국</li>
                          </ul>
                        </td>
                        <td>
                          <ul>
                            <li>쌀밥</li>
                            <li>소고기무국</li>
                            <li>야채계란찜</li>
                            <li>열무순나물</li>
                            <li>김치/요구르트</li>
                            <li>미역국</li>
                          </ul>
                        </td>
                        <td>
                          <ul>
                            <li>쌀밥</li>
                            <li>소고기무국</li>
                            <li>야채계란찜</li>
                            <li>열무순나물</li>
                            <li>김치/요구르트</li>
                            <li>미역국</li>
                          </ul>
                        </td>
                      </tr>
                    </tbody>
                  </Table>

                  <Table striped bordered>
                    <thead>
                      <tr>
                        <th>4주</th>
                        <th>1/22 (일)</th>
                        <th>1/23 (월)</th>
                        <th>1/24 (화)</th>
                        <th>1/25 (수)</th>
                        <th>1/26 (목)</th>
                        <th>1/27 (금)</th>
                        <th>1/28 (토)</th>
                      </tr>
                    </thead>
                    <tbody>
                      <tr>
                        <td>아침</td>
                        <td>
                          <ul>
                            <li>쌀밥</li>
                            <li>소고기무국</li>
                            <li>야채계란찜</li>
                            <li>열무순나물</li>
                            <li>김치/요구르트</li>
                            <li>미역국</li>
                          </ul>
                        </td>
                        <td>
                          <ul>
                            <li>쌀밥</li>
                            <li>소고기무국</li>
                            <li>야채계란찜</li>
                            <li>열무순나물</li>
                            <li>김치/요구르트</li>
                            <li>미역국</li>
                          </ul>
                        </td>
                        <td>
                          <ul>
                            <li>쌀밥</li>
                            <li>소고기무국</li>
                            <li>야채계란찜</li>
                            <li>열무순나물</li>
                            <li>김치/요구르트</li>
                            <li>미역국</li>
                          </ul>
                        </td>
                        <td>
                          <ul>
                            <li>쌀밥</li>
                            <li>소고기무국</li>
                            <li>야채계란찜</li>
                            <li>열무순나물</li>
                            <li>김치/요구르트</li>
                            <li>미역국</li>
                          </ul>
                        </td>
                        <td>
                          <ul>
                            <li>쌀밥</li>
                            <li>소고기무국</li>
                            <li>야채계란찜</li>
                            <li>열무순나물</li>
                            <li>김치/요구르트</li>
                            <li>미역국</li>
                          </ul>
                        </td>
                        <td>
                          <ul>
                            <li>쌀밥</li>
                            <li>소고기무국</li>
                            <li>야채계란찜</li>
                            <li>열무순나물</li>
                            <li>김치/요구르트</li>
                            <li>미역국</li>
                          </ul>
                        </td>
                        <td>
                          <ul>
                            <li>쌀밥</li>
                            <li>소고기무국</li>
                            <li>야채계란찜</li>
                            <li>열무순나물</li>
                            <li>김치/요구르트</li>
                            <li>미역국</li>
                          </ul>
                        </td>
                      </tr>
                      <tr>
                        <td>점심</td>
                        <td>
                          <ul>
                            <li>쌀밥</li>
                            <li>소고기무국</li>
                            <li>야채계란찜</li>
                            <li>열무순나물</li>
                            <li>김치/요구르트</li>
                            <li>미역국</li>
                          </ul>
                        </td>
                        <td>
                          <ul>
                            <li>쌀밥</li>
                            <li>소고기무국</li>
                            <li>야채계란찜</li>
                            <li>열무순나물</li>
                            <li>김치/요구르트</li>
                            <li>미역국</li>
                          </ul>
                        </td>
                        <td>
                          <ul>
                            <li>쌀밥</li>
                            <li>소고기무국</li>
                            <li>야채계란찜</li>
                            <li>열무순나물</li>
                            <li>김치/요구르트</li>
                            <li>미역국</li>
                          </ul>
                        </td>
                        <td>
                          <ul>
                            <li>쌀밥</li>
                            <li>소고기무국</li>
                            <li>야채계란찜</li>
                            <li>열무순나물</li>
                            <li>김치/요구르트</li>
                            <li>미역국</li>
                          </ul>
                        </td>
                        <td>
                          <ul>
                            <li>쌀밥</li>
                            <li>소고기무국</li>
                            <li>야채계란찜</li>
                            <li>열무순나물</li>
                            <li>김치/요구르트</li>
                            <li>미역국</li>
                          </ul>
                        </td>
                        <td>
                          <ul>
                            <li>쌀밥</li>
                            <li>소고기무국</li>
                            <li>야채계란찜</li>
                            <li>열무순나물</li>
                            <li>김치/요구르트</li>
                            <li>미역국</li>
                          </ul>
                        </td>
                        <td>
                          <ul>
                            <li>쌀밥</li>
                            <li>소고기무국</li>
                            <li>야채계란찜</li>
                            <li>열무순나물</li>
                            <li>김치/요구르트</li>
                            <li>미역국</li>
                          </ul>
                        </td>
                      </tr>
                      <tr>
                        <td>저녁</td>
                        <td>
                          <ul>
                            <li>쌀밥</li>
                            <li>소고기무국</li>
                            <li>야채계란찜</li>
                            <li>열무순나물</li>
                            <li>김치/요구르트</li>
                            <li>미역국</li>
                          </ul>
                        </td>
                        <td>
                          <ul>
                            <li>쌀밥</li>
                            <li>소고기무국</li>
                            <li>야채계란찜</li>
                            <li>열무순나물</li>
                            <li>김치/요구르트</li>
                            <li>미역국</li>
                          </ul>
                        </td>
                        <td>
                          <ul>
                            <li>쌀밥</li>
                            <li>소고기무국</li>
                            <li>야채계란찜</li>
                            <li>열무순나물</li>
                            <li>김치/요구르트</li>
                            <li>미역국</li>
                          </ul>
                        </td>
                        <td>
                          <ul>
                            <li>쌀밥</li>
                            <li>소고기무국</li>
                            <li>야채계란찜</li>
                            <li>열무순나물</li>
                            <li>김치/요구르트</li>
                            <li>미역국</li>
                          </ul>
                        </td>
                        <td>
                          <ul>
                            <li>쌀밥</li>
                            <li>소고기무국</li>
                            <li>야채계란찜</li>
                            <li>열무순나물</li>
                            <li>김치/요구르트</li>
                            <li>미역국</li>
                          </ul>
                        </td>
                        <td>
                          <ul>
                            <li>쌀밥</li>
                            <li>소고기무국</li>
                            <li>야채계란찜</li>
                            <li>열무순나물</li>
                            <li>김치/요구르트</li>
                            <li>미역국</li>
                          </ul>
                        </td>
                        <td>
                          <ul>
                            <li>쌀밥</li>
                            <li>소고기무국</li>
                            <li>야채계란찜</li>
                            <li>열무순나물</li>
                            <li>김치/요구르트</li>
                            <li>미역국</li>
                          </ul>
                        </td>
                      </tr>
                    </tbody>
                  </Table>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default CurriculumMenu;
